/**
 * Diff utility — compares extracted labor data vs existing data
 */

const SKIP_KEYS = ["_confidence", "_sources", "_notes", "_diff"];

export function diffLaborData(existing, extracted, countryId) {
  const diffs = [];
  const keys = Object.keys(extracted).filter(k => !SKIP_KEYS.includes(k));

  for (const key of keys) {
    const oldVal = existing[key];
    const newVal = extracted[key];
    if (newVal === null) continue; // Claude couldn't find it — skip
    if (oldVal === undefined) continue; // New field — skip for now
    if (String(oldVal).trim() !== String(newVal).trim()) {
      diffs.push({ field: key, old: oldVal, new: newVal });
    }
  }
  return diffs;
}

export function formatDiffReport(results, date) {
  const lines = [
    `# Labor Law Sync Report — ${date}`,
    "",
    `Generated by: scripts/labor-sync/extract.js`,
    `Model: claude-opus-4-6`,
    "",
    "---",
    "",
  ];

  for (const r of results) {
    if (!r) continue;
    const { id, name, data } = r;
    const conf = ((data._confidence ?? 0) * 100).toFixed(0);
    const diffs = data._diff ?? [];
    const status = diffs.length > 0 ? "🟡 CHANGES DETECTED" : "✅ No changes";
    const confIcon = data._confidence >= 0.85 ? "🔵" : data._confidence >= 0.7 ? "🟢" : "🟠";

    lines.push(`## ${name} (${id})`);
    lines.push(`${confIcon} Confidence: ${conf}% | ${status}`);
    lines.push("");

    if (diffs.length > 0) {
      lines.push("| Field | Current | Extracted |");
      lines.push("|-------|---------|-----------|");
      for (const d of diffs) {
        lines.push(`| \`${d.field}\` | ${d.old} | **${d.new}** |`);
      }
      lines.push("");
    }

    if (data._notes) {
      lines.push(`> **Notes:** ${data._notes}`);
      lines.push("");
    }

    if (data._sources?.length) {
      lines.push(`Sources: ${data._sources.join(", ")}`);
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  lines.push("### Action Required");
  lines.push("");
  lines.push("For any 🟡 rows above:");
  lines.push("1. Verify change against official source link");
  lines.push("2. Update `src/data/countries.js` if confirmed");
  lines.push("3. Update `existing-data.js` snapshot");

  return lines.join("\n");
}
